// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NileCareAPI.Data;

#nullable disable

namespace NileCareAPI.Migrations
{
    [DbContext(typeof(NileCareDbContextV2))]
    [Migration("20251128152841_AddQueueNumber")]
    partial class AddQueueNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NileCareAPI.Models.AdminUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("NileCareAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWheelchairAccessible")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "stefan-mueller-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f25889d4-b1a1-4fd4-918f-88062c3a1699",
                            Email = "stefan.mueller@email.com",
                            EmailConfirmed = true,
                            FirstName = "Stefan",
                            IsWheelchairAccessible = false,
                            LastName = "Mueller",
                            LockoutEnabled = false,
                            NormalizedEmail = "STEFAN.MUELLER@EMAIL.COM",
                            NormalizedUserName = "STEFAN.MUELLER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENFt5Rstu1CZVfxJnjPBjRkKEqW7kjlryGQgMhJhxHH8mDB3P+Fbt8Vuai11rWN+tg==",
                            PhoneNumber = "+20 123 456 7890",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "/images/default-avatar.png",
                            SecurityStamp = "d4a88dbe-8684-4fd7-99bf-caa1070ca734",
                            TwoFactorEnabled = false,
                            UserName = "stefan.mueller@email.com"
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LegacyDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PatientNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("LegacyDoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AppointmentDate = new DateTime(2025, 11, 21, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5462),
                            AppointmentType = "In-Person",
                            ConsultationFee = 500m,
                            CreatedAt = new DateTime(2025, 11, 18, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5475),
                            DoctorNotes = "Patient responding well to medication. ECG shows improvement.",
                            DoctorUserId = "dr-ahmed-hassan-id",
                            PatientNotes = "Follow-up for atrial fibrillation treatment",
                            PaymentStatus = "Paid",
                            QueueNumber = 0,
                            Status = "Completed",
                            UpdatedAt = new DateTime(2025, 11, 21, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5476),
                            UserId = "stefan-mueller-id"
                        },
                        new
                        {
                            Id = 101,
                            AppointmentDate = new DateTime(2025, 11, 14, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5489),
                            AppointmentType = "In-Person",
                            ConsultationFee = 450m,
                            CreatedAt = new DateTime(2025, 11, 11, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5490),
                            DoctorNotes = "Comprehensive cardiac evaluation completed. Recommended specialist referral.",
                            LegacyDoctorId = 2,
                            PatientNotes = "Initial consultation",
                            PaymentStatus = "Paid",
                            QueueNumber = 0,
                            Status = "Completed",
                            UpdatedAt = new DateTime(2025, 11, 14, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5491),
                            UserId = "stefan-mueller-id"
                        },
                        new
                        {
                            Id = 102,
                            AppointmentDate = new DateTime(2025, 12, 3, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5493),
                            AppointmentType = "In-Person",
                            ConsultationFee = 500m,
                            CreatedAt = new DateTime(2025, 11, 26, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5495),
                            DoctorNotes = "",
                            DoctorUserId = "dr-ahmed-hassan-id",
                            PatientNotes = "Pre-procedure consultation",
                            PaymentStatus = "Unpaid",
                            QueueNumber = 0,
                            Status = "Confirmed",
                            UserId = "stefan-mueller-id"
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("NileCareAPI.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Hospital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Leading cardiac electrophysiologist",
                            City = "Cairo",
                            ConsultationFee = 500m,
                            Hospital = "Cairo Heart Institute",
                            ImageUrl = "/images/doctors/dr-ahmed-hassan.jpg",
                            Languages = "Arabic,English,German",
                            Name = "Dr. Ahmed Hassan",
                            Rating = 4.9000000000000004,
                            Specialty = "Cardiology",
                            SpecialtyTags = "Atrial Fibrillation,Cardiac Ablation,Heart Arrhythmia,Cardiovascular",
                            YearsOfExperience = 18
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Experienced cardiologist",
                            City = "Cairo",
                            ConsultationFee = 450m,
                            Hospital = "Nile Medical Center",
                            ImageUrl = "/images/doctors/dr-fatima-elsayed.jpg",
                            Languages = "Arabic,English,French",
                            Name = "Dr. Fatima El-Sayed",
                            Rating = 4.7000000000000002,
                            Specialty = "Cardiology",
                            SpecialtyTags = "Heart Disease,Cardiology,Preventive Cardiology",
                            YearsOfExperience = 15
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.DoctorUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hospital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DoctorUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dr-ahmed-hassan-id",
                            AccessFailedCount = 0,
                            Bio = "Leading cardiac electrophysiologist specializing in atrial fibrillation treatment",
                            City = "Cairo",
                            ConcurrencyStamp = "c623b03e-2fc7-42fb-aec2-816c536e3388",
                            ConsultationFee = 500m,
                            Email = "dr.ahmed@nileheart.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmed",
                            Hospital = "Cairo Heart Institute",
                            ImageUrl = "/images/doctors/dr-ahmed-hassan.jpg",
                            IsAvailable = true,
                            Languages = "Arabic,English,German",
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "DR.AHMED@NILEHEART.COM",
                            NormalizedUserName = "DR.AHMED@NILEHEART.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDdxliK5ARDi/nmrqd3f9ZUhTva3EdGfZ1h3ssK369/2aAqdl+jm4I8NhJdv0xXb2Q==",
                            PhoneNumber = "+20 100 234 5678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d53fb80-fdb4-47c9-9c1b-1d4709f1247b",
                            Specialty = "Cardiology",
                            SpecialtyTags = "Atrial Fibrillation,Cardiac Ablation,Heart Arrhythmia,Cardiovascular",
                            TwoFactorEnabled = false,
                            UserName = "dr.ahmed@nileheart.com",
                            YearsOfExperience = 18
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeluxeRoomMaxGuests")
                        .HasColumnType("int");

                    b.Property<decimal>("DeluxeRoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ElevatorAccess")
                        .HasColumnType("bit");

                    b.Property<int>("FamilyRoomMaxGuests")
                        .HasColumnType("int");

                    b.Property<decimal>("FamilyRoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("GrabBars")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RollInShower")
                        .HasColumnType("bit");

                    b.Property<int>("StandardRoomMaxGuests")
                        .HasColumnType("int");

                    b.Property<decimal>("StandardRoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SuiteRoomMaxGuests")
                        .HasColumnType("int");

                    b.Property<decimal>("SuiteRoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("WheelchairAccessible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Corniche El Nil, Downtown Cairo",
                            Amenities = "Free WiFi,Pool,Gym,Restaurant,Room Service",
                            ApprovalStatus = "Approved",
                            City = "Cairo",
                            CreatedAt = new DateTime(2025, 11, 28, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5339),
                            DeluxeRoomMaxGuests = 3,
                            DeluxeRoomPrice = 180m,
                            Description = "Luxury hotel with full accessibility",
                            ElevatorAccess = true,
                            FamilyRoomMaxGuests = 6,
                            FamilyRoomPrice = 350m,
                            GrabBars = true,
                            ImageUrl = "/images/hotels/nile-plaza.jpg",
                            Name = "Nile Plaza Hotel",
                            OwnerId = "hotel-owner-nile-id",
                            PricePerNight = 120m,
                            Rating = 4.5,
                            RollInShower = true,
                            StandardRoomMaxGuests = 2,
                            StandardRoomPrice = 120m,
                            SuiteRoomMaxGuests = 4,
                            SuiteRoomPrice = 280m,
                            WheelchairAccessible = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Tahrir Square, Cairo",
                            Amenities = "Free WiFi,Restaurant",
                            ApprovalStatus = "Approved",
                            City = "Cairo",
                            CreatedAt = new DateTime(2025, 11, 28, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5345),
                            DeluxeRoomMaxGuests = 3,
                            DeluxeRoomPrice = 140m,
                            Description = "Comfortable hotel in central Cairo",
                            ElevatorAccess = true,
                            FamilyRoomMaxGuests = 6,
                            FamilyRoomPrice = 280m,
                            GrabBars = true,
                            ImageUrl = "/images/hotels/cairo-grand.jpg",
                            Name = "Cairo Grand",
                            OwnerId = "hotel-owner-nile-id",
                            PricePerNight = 95m,
                            Rating = 4.2000000000000002,
                            RollInShower = false,
                            StandardRoomMaxGuests = 2,
                            StandardRoomPrice = 95m,
                            SuiteRoomMaxGuests = 4,
                            SuiteRoomPrice = 220m,
                            WheelchairAccessible = true
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.HotelBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoomRatePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("HotelBookings");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CheckInDate = new DateTime(2025, 11, 18, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5547),
                            CheckOutDate = new DateTime(2025, 11, 21, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5547),
                            CreatedAt = new DateTime(2025, 11, 13, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5550),
                            HotelId = 1,
                            NumberOfGuests = 2,
                            PaymentStatus = "Paid",
                            RoomRatePerNight = 120m,
                            RoomType = "Deluxe Accessible Room",
                            SpecialRequests = "Ground floor room with roll-in shower",
                            Status = "Completed",
                            UserId = "stefan-mueller-id"
                        },
                        new
                        {
                            Id = 101,
                            CheckInDate = new DateTime(2025, 12, 1, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5551),
                            CheckOutDate = new DateTime(2025, 12, 5, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5552),
                            CreatedAt = new DateTime(2025, 11, 25, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5554),
                            HotelId = 2,
                            NumberOfGuests = 1,
                            PaymentStatus = "Unpaid",
                            RoomRatePerNight = 95m,
                            RoomType = "Standard Accessible Room",
                            SpecialRequests = "Near elevator",
                            Status = "Confirmed",
                            UserId = "stefan-mueller-id"
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.HotelImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelImages");
                });

            modelBuilder.Entity("NileCareAPI.Models.HotelUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HotelUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "hotel-owner-nile-id",
                            AccessFailedCount = 0,
                            CompanyName = "Nile Hotels Group",
                            ConcurrencyStamp = "96a621a0-3e99-428b-84f7-d7b5c4d99891",
                            CreatedAt = new DateTime(2025, 11, 28, 15, 28, 40, 585, DateTimeKind.Utc).AddTicks(2731),
                            Email = "hotel@nilehotels.com",
                            EmailConfirmed = true,
                            FirstName = "Mohamed",
                            LastName = "Farouk",
                            LockoutEnabled = false,
                            NormalizedEmail = "HOTEL@NILEHOTELS.COM",
                            NormalizedUserName = "HOTEL@NILEHOTELS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1r+a3pSFgdLCt07hH+aIdR1ZPdGWcm/5dMjhDSH1631t0lchnkNeEPaWhmBneKZA==",
                            PhoneNumber = "+20 100 555 1234",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "/images/default-avatar.png",
                            SecurityStamp = "e87cda2b-74ce-4132-a8a4-76b1de2c7cf7",
                            TwoFactorEnabled = false,
                            UserName = "hotel@nilehotels.com"
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.MedicalProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessibilityNeeds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MedicalProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessibilityNeeds = "Wheelchair access required",
                            ConsentGiven = true,
                            CreatedAt = new DateTime(2025, 11, 28, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5061),
                            MedicalConditions = "Atrial Fibrillation",
                            TreatmentHistory = "Diagnosed 2023, currently on blood thinners",
                            UpdatedAt = new DateTime(2025, 11, 28, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5062),
                            UserId = "stefan-mueller-id"
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("NileCareAPI.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("NileCareAPI.Models.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WheelchairAccessible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Description = "Spacious van with hydraulic lift",
                            Features = "Hydraulic Lift,Wheelchair Locks,Air Conditioning",
                            ImageUrl = "/images/transport/wheelchair-van.jpg",
                            PricePerHour = 25m,
                            VehicleType = "Wheelchair Accessible Van",
                            WheelchairAccessible = true
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            Description = "Comfortable sedan",
                            Features = "Air Conditioning,Professional Driver",
                            ImageUrl = "/images/transport/sedan.jpg",
                            PricePerHour = 15m,
                            VehicleType = "Standard Sedan",
                            WheelchairAccessible = false
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 6,
                            Description = "Premium SUV with extra space",
                            Features = "Leather Seats,Air Conditioning,WiFi,Professional Driver",
                            ImageUrl = "/images/transport/suv.jpg",
                            PricePerHour = 35m,
                            VehicleType = "Luxury SUV",
                            WheelchairAccessible = false
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2,
                            Description = "Lightweight, easy to maneuver, ideal for quick trips.",
                            Features = "Compact storage space, easy parking.",
                            ImageUrl = "/images/transport/OIP.webp",
                            PricePerHour = 10m,
                            VehicleType = "Scooter",
                            WheelchairAccessible = false
                        });
                });

            modelBuilder.Entity("NileCareAPI.Models.TransportBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransportId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.HasIndex("UserId");

                    b.ToTable("TransportBookings");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5800),
                            DropoffLocation = "Nile Plaza Hotel",
                            NumberOfPassengers = 2,
                            PaymentStatus = "Paid",
                            PickupDateTime = new DateTime(2025, 11, 18, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5794),
                            PickupLocation = "Cairo International Airport",
                            SpecialRequests = "Wheelchair assistance needed",
                            Status = "Completed",
                            TotalPrice = 50m,
                            TransportId = 1,
                            UserId = "stefan-mueller-id"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2025, 11, 20, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5804),
                            DropoffLocation = "Cairo Heart Institute",
                            NumberOfPassengers = 1,
                            PaymentStatus = "Paid",
                            PickupDateTime = new DateTime(2025, 11, 21, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5802),
                            PickupLocation = "Nile Plaza Hotel",
                            SpecialRequests = "Wheelchair accessible required",
                            Status = "Completed",
                            TotalPrice = 50m,
                            TransportId = 1,
                            UserId = "stefan-mueller-id"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2025, 11, 26, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5806),
                            DropoffLocation = "Cairo Heart Institute",
                            NumberOfPassengers = 1,
                            PaymentStatus = "Unpaid",
                            PickupDateTime = new DateTime(2025, 12, 3, 15, 28, 40, 659, DateTimeKind.Utc).AddTicks(5805),
                            PickupLocation = "Cairo Grand Hotel",
                            SpecialRequests = "",
                            Status = "Confirmed",
                            TotalPrice = 30m,
                            TransportId = 2,
                            UserId = "stefan-mueller-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NileCareAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NileCareAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NileCareAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NileCareAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NileCareAPI.Models.Appointment", b =>
                {
                    b.HasOne("NileCareAPI.Models.DoctorUser", "DoctorUser")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NileCareAPI.Models.Doctor", "LegacyDoctor")
                        .WithMany("Appointments")
                        .HasForeignKey("LegacyDoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NileCareAPI.Models.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorUser");

                    b.Navigation("LegacyDoctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NileCareAPI.Models.ChatMessage", b =>
                {
                    b.HasOne("NileCareAPI.Models.DoctorUser", "Doctor")
                        .WithMany("ChatMessages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NileCareAPI.Models.ApplicationUser", "Patient")
                        .WithMany("ChatMessages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NileCareAPI.Models.Doctor", b =>
                {
                    b.OwnsMany("AvailabilitySlot", "AvailabilitySlots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Day")
                                .HasColumnType("int");

                            b1.Property<int?>("DoctorId")
                                .IsRequired()
                                .HasColumnType("int");

                            b1.Property<int?>("DoctorId1")
                                .HasColumnType("int");

                            b1.Property<string>("DoctorUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<TimeSpan>("End")
                                .HasColumnType("time");

                            b1.Property<TimeSpan>("Start")
                                .HasColumnType("time");

                            b1.HasKey("Id");

                            b1.HasIndex("DoctorId");

                            b1.HasIndex("DoctorId1");

                            b1.HasIndex("DoctorUserId");

                            b1.ToTable("Doctors_AvailabilitySlots");

                            b1.WithOwner()
                                .HasForeignKey("DoctorId");

                            b1.HasOne("NileCareAPI.Models.Doctor", "Doctor")
                                .WithMany()
                                .HasForeignKey("DoctorId1");

                            b1.HasOne("NileCareAPI.Models.DoctorUser", "DoctorUser")
                                .WithMany()
                                .HasForeignKey("DoctorUserId");

                            b1.Navigation("Doctor");

                            b1.Navigation("DoctorUser");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    Day = 1,
                                    DoctorId = 1,
                                    End = new TimeSpan(0, 14, 0, 0, 0),
                                    Start = new TimeSpan(0, 9, 0, 0, 0)
                                },
                                new
                                {
                                    Id = 2,
                                    Day = 3,
                                    DoctorId = 1,
                                    End = new TimeSpan(0, 16, 0, 0, 0),
                                    Start = new TimeSpan(0, 10, 0, 0, 0)
                                },
                                new
                                {
                                    Id = 3,
                                    Day = 0,
                                    DoctorId = 2,
                                    End = new TimeSpan(0, 12, 30, 0, 0),
                                    Start = new TimeSpan(0, 8, 30, 0, 0)
                                },
                                new
                                {
                                    Id = 4,
                                    Day = 2,
                                    DoctorId = 2,
                                    End = new TimeSpan(0, 17, 0, 0, 0),
                                    Start = new TimeSpan(0, 11, 0, 0, 0)
                                });
                        });

                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("NileCareAPI.Models.DoctorUser", b =>
                {
                    b.OwnsMany("AvailabilitySlot", "AvailabilitySlots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Day")
                                .HasColumnType("int");

                            b1.Property<int?>("DoctorId")
                                .HasColumnType("int");

                            b1.Property<string>("DoctorUserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DoctorUserId1")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<TimeSpan>("End")
                                .HasColumnType("time");

                            b1.Property<TimeSpan>("Start")
                                .HasColumnType("time");

                            b1.HasKey("Id");

                            b1.HasIndex("DoctorId");

                            b1.HasIndex("DoctorUserId");

                            b1.HasIndex("DoctorUserId1");

                            b1.ToTable("DoctorUsers_AvailabilitySlots");

                            b1.HasOne("NileCareAPI.Models.Doctor", "Doctor")
                                .WithMany()
                                .HasForeignKey("DoctorId");

                            b1.WithOwner()
                                .HasForeignKey("DoctorUserId");

                            b1.HasOne("NileCareAPI.Models.DoctorUser", "DoctorUser")
                                .WithMany()
                                .HasForeignKey("DoctorUserId1");

                            b1.Navigation("Doctor");

                            b1.Navigation("DoctorUser");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    Day = 1,
                                    DoctorUserId = "dr-ahmed-hassan-id",
                                    End = new TimeSpan(0, 14, 0, 0, 0),
                                    Start = new TimeSpan(0, 9, 0, 0, 0)
                                },
                                new
                                {
                                    Id = 2,
                                    Day = 3,
                                    DoctorUserId = "dr-ahmed-hassan-id",
                                    End = new TimeSpan(0, 16, 0, 0, 0),
                                    Start = new TimeSpan(0, 10, 0, 0, 0)
                                });
                        });

                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("NileCareAPI.Models.Hotel", b =>
                {
                    b.HasOne("NileCareAPI.Models.HotelUser", "Owner")
                        .WithMany("Hotels")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NileCareAPI.Models.HotelBooking", b =>
                {
                    b.HasOne("NileCareAPI.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NileCareAPI.Models.ApplicationUser", "User")
                        .WithMany("HotelBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NileCareAPI.Models.HotelImage", b =>
                {
                    b.HasOne("NileCareAPI.Models.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("NileCareAPI.Models.MedicalProfile", b =>
                {
                    b.HasOne("NileCareAPI.Models.ApplicationUser", "User")
                        .WithOne("MedicalProfile")
                        .HasForeignKey("NileCareAPI.Models.MedicalProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NileCareAPI.Models.MedicalRecord", b =>
                {
                    b.HasOne("NileCareAPI.Models.ApplicationUser", "User")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NileCareAPI.Models.Payment", b =>
                {
                    b.HasOne("NileCareAPI.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NileCareAPI.Models.TransportBooking", b =>
                {
                    b.HasOne("NileCareAPI.Models.Transport", "Transport")
                        .WithMany()
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NileCareAPI.Models.ApplicationUser", "User")
                        .WithMany("TransportBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NileCareAPI.Models.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ChatMessages");

                    b.Navigation("HotelBookings");

                    b.Navigation("MedicalProfile");

                    b.Navigation("MedicalRecords");

                    b.Navigation("TransportBookings");
                });

            modelBuilder.Entity("NileCareAPI.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("NileCareAPI.Models.DoctorUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("NileCareAPI.Models.Hotel", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("NileCareAPI.Models.HotelUser", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
